/**
 * config.js
 *
 * Single import point for the HuggingFace Transformers library and
 * the MODEL_CONFIGS lookup table that describes every supported VLM.
 */

export {
  AutoProcessor,
  AutoTokenizer,
  AutoModelForVision2Seq,
  AutoModelForImageTextToText,
  Qwen2VLForConditionalGeneration,
  Florence2ForConditionalGeneration,
  PaliGemmaForConditionalGeneration,
  Gemma4ForConditionalGeneration,
  Moondream1ForConditionalGeneration,
  MultiModalityCausalLM,
  RawImage,
} from "https://cdn.jsdelivr.net/npm/@huggingface/transformers/dist/transformers.min.js";

export const MODEL_CONFIGS = {
  "smolvlm-256m": {
    modelId: "HuggingFaceTB/SmolVLM-256M-Instruct",
    displayName: "SmolVLM 256M (Fast)",
    modelClass: "AutoModelForVision2Seq",
    processorType: "smolvlm",
    vramEstimate: "~0.5GB",
    maxTokens: 100,
    suggestedInterval: "0",
    showWarning: false,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "q4",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: true,
  },
  "smolvlm-500m": {
    modelId: "HuggingFaceTB/SmolVLM-500M-Instruct",
    displayName: "SmolVLM 500M (Balanced)",
    modelClass: "AutoModelForVision2Seq",
    processorType: "smolvlm",
    vramEstimate: "~1GB",
    maxTokens: 100,
    suggestedInterval: "100",
    showWarning: false,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "q4",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: true,
  },
  "smolvlm-2b": {
    modelId: "HuggingFaceTB/SmolVLM-Instruct",
    displayName: "SmolVLM 2B (Capable)",
    modelClass: "AutoModelForVision2Seq",
    processorType: "smolvlm",
    vramEstimate: "~4GB",
    maxTokens: 150,
    suggestedInterval: "500",
    showWarning: true,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "q4",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: true,
  },
  "fastvlm-05b": {
    modelId: "onnx-community/FastVLM-0.5B-ONNX",
    displayName: "FastVLM 0.5B (Apple)",
    modelClass: "AutoModelForImageTextToText",
    processorType: "fastvlm",
    vramEstimate: "~1GB",
    maxTokens: 100,
    suggestedInterval: "0",
    showWarning: false,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "q4",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: true,
  },
  "qwen2vl-2b": {
    modelId: "onnx-community/Qwen2-VL-2B-Instruct",
    displayName: "Qwen2-VL 2B (Alibaba)",
    modelClass: "Qwen2VLForConditionalGeneration",
    processorType: "qwen2vl",
    vramEstimate: "~4GB",
    maxTokens: 150,
    suggestedInterval: "500",
    showWarning: true,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "q4",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: true,
    imageSize: 448,
  },
  "florence2-base": {
    modelId: "onnx-community/Florence-2-base-ft",
    displayName: "Florence-2 Base (Microsoft)",
    modelClass: "Florence2ForConditionalGeneration",
    processorType: "florence",
    vramEstimate: "~0.5GB",
    maxTokens: 150,
    suggestedInterval: "100",
    showWarning: false,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "q4",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: false,
    defaultPrompt: "<MORE_DETAILED_CAPTION>",
  },
  "florence2-large": {
    modelId: "onnx-community/Florence-2-large-ft",
    displayName: "Florence-2 Large (Microsoft)",
    modelClass: "Florence2ForConditionalGeneration",
    processorType: "florence",
    vramEstimate: "~1.5GB",
    maxTokens: 200,
    suggestedInterval: "250",
    showWarning: false,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "q4",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: false,
    defaultPrompt: "<MORE_DETAILED_CAPTION>",
  },
  "paligemma2-3b": {
    modelId: "onnx-community/paligemma2-3b-pt-224",
    displayName: "PaliGemma2 3B (Google)",
    modelClass: "PaliGemmaForConditionalGeneration",
    processorType: "paligemma",
    vramEstimate: "~6GB",
    maxTokens: 150,
    suggestedInterval: "1000",
    showWarning: true,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "q4",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: false,
    imageSize: 224,
  },
  "gemma4-e2b": {
    modelId: "onnx-community/gemma-4-E2B-it-ONNX",
    displayName: "Gemma 4 E2B (Google)",
    modelClass: "Gemma4ForConditionalGeneration",
    processorType: "gemma4",
    vramEstimate: "~4GB",
    maxTokens: 150,
    suggestedInterval: "500",
    showWarning: true,
    dtype: "q4f16",
    chatTemplateSupported: true,
  },
  "gemma4-e4b": {
    modelId: "onnx-community/gemma-4-E4B-it-ONNX",
    displayName: "Gemma 4 E4B (Google)",
    modelClass: "Gemma4ForConditionalGeneration",
    processorType: "gemma4",
    vramEstimate: "~6GB",
    maxTokens: 150,
    suggestedInterval: "1000",
    showWarning: true,
    dtype: "q4f16",
    chatTemplateSupported: true,
  },
  "moondream2": {
    modelId: "Xenova/moondream2",
    displayName: "Moondream2 (Xenova)",
    modelClass: "Moondream1ForConditionalGeneration",
    processorType: "moondream",
    vramEstimate: "~2GB",
    maxTokens: 128,
    suggestedInterval: "250",
    showWarning: false,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "fp16",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: false,
    requiresTokenizer: true,
  },
  "janus-pro-1b": {
    modelId: "onnx-community/Janus-Pro-1B-ONNX",
    displayName: "Janus-Pro 1B (DeepSeek)",
    modelClass: "MultiModalityCausalLM",
    processorType: "janus",
    vramEstimate: "~2GB",
    maxTokens: 150,
    suggestedInterval: "250",
    showWarning: false,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "q4",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: false,
  },
  "janus-1.3b": {
    modelId: "onnx-community/Janus-1.3B-ONNX",
    displayName: "Janus 1.3B (DeepSeek)",
    modelClass: "MultiModalityCausalLM",
    processorType: "janus",
    vramEstimate: "~2.5GB",
    maxTokens: 150,
    suggestedInterval: "500",
    showWarning: false,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "q4",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: false,
  },
  "florence2-base-pretrain": {
    modelId: "onnx-community/Florence-2-base",
    displayName: "Florence-2 Base PT (Microsoft)",
    modelClass: "Florence2ForConditionalGeneration",
    processorType: "florence",
    vramEstimate: "~0.5GB",
    maxTokens: 150,
    suggestedInterval: "100",
    showWarning: false,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "q4",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: false,
    defaultPrompt: "<MORE_DETAILED_CAPTION>",
  },
  "phi3-vision": {
    modelId: "onnx-community/Phi-3-vision-128k-instruct",
    displayName: "Phi-3 Vision (Microsoft)",
    modelClass: "AutoModelForImageTextToText",
    processorType: "phi3v",
    vramEstimate: "~8GB",
    maxTokens: 200,
    suggestedInterval: "1000",
    showWarning: true,
    dtype: {
      embed_tokens: "fp16",
      vision_encoder: "q4",
      decoder_model_merged: "q4",
    },
    chatTemplateSupported: true,
  },
};
